name: Create package

on:
  workflow_call:
    inputs:
      pkg-name:
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  ORGANIZATION: bushido-games

jobs:
  create-pkg:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get app version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Download packages dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: packages_dist-${{ github.run_id }}-${{ github.run_number }}
          path: ./packages

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ${{ inputs.pkg-name }} package
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./packages/${{ inputs.pkg-name }}/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/bushido-${{ inputs.pkg-name }}:${{ steps.package-version.outputs.current-version}}
